export const CHANGE_WINDOW_SIZE = 'browser/CHANGE_WINDOW_SIZE';

export const CHANGE_FETCHING_STATE = 'zipCodes/CHANGE_FETCHING_STATE';
export const CHANGE_SEARCH_VALUE = 'zipCodes/CHANGE_SEARCH_VALUE';
export const CHANGE_ERROR_VALUE = 'zipCodes/CHANGE_ERROR_VALUE';
export const CHANGE_CODES_VALUES = 'zipCodes/CHANGE_CODES_VALUES';
export const CHANGE_CURRENT_ITEM = 'zipCodes/CHANGE_CURRENT_ITEM';
export const SET_INITIAL_STATE = 'zipCodes/SET_INITIAL_STATE';
export const ITEM_FETCHED_SUCCESS = 'zipCodes/ITEM_FETCHED_SUCCESS';
export const ITEM_FETCHED_ERROR = 'zipCodes/ITEM_FETCHED_ERROR';
